import type { AssetTypeConfig } from '../types';

export const ASSET_TYPES: AssetTypeConfig[] = [
  {
    id: 'furniture',
    label: 'Furniture',
    icon: '🪑',
    hint: 'Draw front view. Rects → boxes, circles → soft forms.',
    defaultMode: 'extrude',
    defaultDepth: 0.55,
    bevel: true,
    bevelSize: 0.04,
    bevelSegments: 3,
    latheSegments: 32,
  },
  {
    id: 'characters',
    label: 'Characters',
    icon: '👤',
    hint: '⭕ head → sphere · lines/thin shapes → limbs · rects → body blocks',
    defaultMode: 'extrude',
    defaultDepth: 0.4,
    bevel: true,
    bevelSize: 0.06,
    bevelSegments: 5,
    latheSegments: 32,
  },
  {
    id: 'buildings',
    label: 'Buildings',
    icon: '🏢',
    hint: 'Draw top-down floor plan — walls extrude upward',
    defaultMode: 'extrude',
    defaultDepth: 1.6,
    bevel: false,
    bevelSize: 0,
    bevelSegments: 1,
    latheSegments: 32,
  },
  {
    id: 'vehicles',
    label: 'Vehicles',
    icon: '🚗',
    hint: 'Draw side profile — extruded across width',
    defaultMode: 'extrude',
    defaultDepth: 1.4,
    bevel: true,
    bevelSize: 0.05,
    bevelSegments: 3,
    latheSegments: 32,
  },
  {
    id: 'jewellery',
    label: 'Jewellery',
    icon: '💍',
    hint: 'Draw cross-section — revolved into a ring or gem',
    defaultMode: 'lathe',
    defaultDepth: 0.5,
    bevel: false,
    bevelSize: 0,
    bevelSegments: 1,
    latheSegments: 48,
  },
  {
    id: 'plushies',
    label: 'Plushies',
    icon: '🧸',
    hint: 'Draw front view — soft rounded extrusion',
    defaultMode: 'extrude',
    defaultDepth: 0.35,
    bevel: true,
    bevelSize: 0.12,
    bevelSegments: 6,
    latheSegments: 32,
  },
  {
    id: 'shoes',
    label: 'Shoes',
    icon: '👟',
    hint: 'Draw side profile — extruded sole & upper',
    defaultMode: 'extrude',
    defaultDepth: 1.0,
    bevel: true,
    bevelSize: 0.06,
    bevelSegments: 4,
    latheSegments: 32,
  },
];

export const PRESET_COLORS = [
  '#ffffff',
  '#fdf2f8',
  '#f9a8d4',
  '#e879a9',
  '#f472b6',
  '#fb7185',
  '#f87171',
  '#fb923c',
  '#fbbf24',
  '#34d399',
  '#60a5fa',
  '#1c1917',
];

export const MATERIAL_PRESETS = [
  { name: 'Matte', metalness: 0, roughness: 0.9 },
  { name: 'Plastic', metalness: 0.1, roughness: 0.4 },
  { name: 'Metal', metalness: 0.9, roughness: 0.2 },
  { name: 'Glass', metalness: 0, roughness: 0.05 },
  { name: 'Rubber', metalness: 0, roughness: 0.95 },
  { name: 'Gold', metalness: 1, roughness: 0.15 },
];
